# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app
COPY examples/config_server.py config_server.py
RUN pip install --no-cache-dir fastmcp
CMD ["python", "config_server.py"]
