name: Run static analysis

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/**"

  # run on all pull requests because these checks are required and will block merges otherwise
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  static_analysis:
    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --dev
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
      - name: Check SDK documentation is up to date
        run: |
          echo "Checking if SDK documentation is up to date..."
          git_status_before=$(git status --porcelain docs/python-sdk/ docs/docs.json 2>/dev/null || true)
          just api-ref-all > /dev/null 2>&1
          git_status_after=$(git status --porcelain docs/python-sdk/ docs/docs.json 2>/dev/null || true)
          if [[ "$git_status_before" != "$git_status_after" ]]; then
            echo "❌ SDK documentation is out of date!"
            echo "Run 'just api-ref-all' and commit the changes."
            git status --porcelain docs/python-sdk/ docs/docs.json
            exit 1
          fi
          echo "✅ SDK documentation is up to date"
